services:
  postgres-sql:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: backend-examples
      POSTGRES_PASSWORD: backend-examples
      POSTGRES_DB: backend-examples
      TZ: Asia/Shanghai
    ports:
      - 5432:5432
  mysql:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: backend-examples
      MYSQL_DATABASE: backend-examples
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    command:
      - --requirepass backend-examples
    environment:
      TZ: Asia/Shanghai
