services:
  postgres-sql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: backend-examples
      POSTGRES_PASSWORD: backend-examples
      POSTGRES_DB: backend-examples
      TZ: Asia/Shanghai
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: backend-examples
      MYSQL_DATABASE: backend-examples
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: backend-examples
      TZ: Asia/Shanghai
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - backend-examples
  mongodb-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: backend-examples
      ME_CONFIG_MONGODB_URL: mongodb://root:backend-examples@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - 8081:8081
    networks:
      - backend-examples
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    command:
      - --requirepass backend-examples
    environment:
      TZ: Asia/Shanghai
  minio:
    image: minio/minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - "./minio/data1:/data1"
      - "./minio/data2:/data2"
    command: server --console-address ":9001" /data{1...2}
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678

networks:
  backend-examples:
    driver: bridge
