// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type BaseResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type HelloRequest struct {
	Name string `json:"message"`
}

type HelloResponse struct {
	BaseResponse
	Data struct {
		Message string `json:"message"`
	}
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	BaseResponse
	Data struct {
		Token string `json:"token"`
	}
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	BaseResponse
	Data struct {
		Message string `json:"message"`
	}
}
