// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type BaseResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type GetUserRequest struct {
	Id int `path:"id"`
}

type GetUserResponse struct {
	BaseResponse
	Data GetUserResponseData `json:"data"`
}

type GetUserResponseData struct {
	Id       int    `json:"id"`
	Username string `json:"username"`
}

type HelloRequest struct {
	Name string `json:"message"`
}

type HelloResponse struct {
	BaseResponse
	Data HelloResponseData `json:"data"`
}

type HelloResponseData struct {
	Message string `json:"message"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	BaseResponse
	Data LoginResponseData `json:"data"`
}

type LoginResponseData struct {
	Token string `json:"token"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	BaseResponse
	Data RegisterResponseData `json:"data"`
}

type RegisterResponseData struct {
	Message string `json:"message"`
}
