# 生成 prisma 客户端
prisma-generate:
	@echo "Generating..."
	npx prisma generate
	# npx prisma generate --schema ./prisma/mysql.prisma 
	# npx prisma generate --schema ./prisma/postgresql.prisma 
	@echo "Done!"
prisma-push:
	@echo "Generating..."
	npx prisma db push
	# npx prisma db push --schema ./prisma/mysql.prisma 
	@echo "Done!"